[package]
name = "aoc19"
version = "0.1.0"
authors = ["Hans Pistor <hpistor@ad.stetson.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "*"
aoc-runner-derive ="*"
pathfinding = "*"
itertools = "*"